### ISSUE TITLE
Maven central sync broken?

### ISSUE THREAD

**Issue by clboettcher** [qaware/majx#32]
1.1.0 is in [bintray](https://bintray.com/qaware-oss/maven/majx/1.1.0#files/de%2Fqaware%2Fmajx%2Fmajx%2F1.1.0) but not in [mvn central](https://mvnrepository.com/artifact/de.qaware.majx/majx)

Sync broken/disabled?

**Comment by lreimer** [comment]
There is no automatic sync. It needs to be done manually on a per version basis.

**Comment by lreimer** [comment]
Also, some of your last publishing activities somehow screwed up the Bintray repository files. Fixed it. Published to Maven central. Please check and verify in a day.

**Comment by clboettcher** [comment]
Oh, i forgot about the sync being manual. Thanks for syncing and fixing bintray. I noticed the wired files too, see https://github.com/qaware/majx/issues/28. Those were added when trying to release 1.1.0 for the first (out of two) attempts. Seems like upgrading the bintray plugin for the second attempt fixed it, see https://github.com/qaware/majx/issues/29. We will see during the next release.

**Comment by clboettcher** [comment]
@lreimer Seems to work now, see https://bintray.com/qaware-oss/maven/majx/1.2.0#files/de/qaware/majx/majx and comment above
